server:
  port: 8092
  servlet:
    context-path: /
dubbo:
  scan:
    basePackages: com.qiuqiu
  application:
    name: provider-user
#  registry:
#    address: zookeeper://192.168.209.129:2181 #?backup=192.168.209.129:2182,192.168.209.129:2183

spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/pages/
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.201.102.30:3306/qiuqiu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
#SpringBoot整合mybatis-plus 使用时切记模式不同
mybatis-plus:
  #定义别名包 当程序自动映射时自动拼接
  type-aliases-package: com.qiuqiu.mapper
  #必须编辑映射文件 在映射文件中编辑sql
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#引入logger日志
logging:
  level:
    #扫描的包路径
    com.jt.mapper: debug