server:
  port: 8091
  servlet:
    context-path: /
dubbo:
  scan:
    basePackages: com.qiuqiu
  application:
    name: provider-user
#  registry:
#    address: zookeeper://192.168.209.129:2181 #?backup=192.168.209.129:2182,192.168.209.129:2183

spring:
  thymeleaf:
    suffix: .html
    prefix:
      classpath:/templates/
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false